services:
  backend:
    image: ${DOCKER_USERNAME}/car-mqtt:latest
    build:
      context: ./car-mqtt
      dockerfile: Dockerfile
    ports:
      - "9180:8080"  # 宿主机 9180 映射到容器 8080（仅用于外部访问）
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    image: ${DOCKER_USERNAME}/vuetify-project:latest
    build:
      context: ./vuetify-project  # 修正上下文路径
      dockerfile: Dockerfile
    ports:
      - "9080:9080"  # 宿主机 9080 → 容器 9080
    depends_on:
      - backend
    restart: unless-stopped
