services:
  backend:
    image: ${DOCKER_USERNAME}/car-mqtt:latest  # 使用环境变量
    build:
      context: ./car-mqtt  # 将上下文切换为 car-mqtt 目录
      dockerfile: Dockerfile  # 直接使用该目录下的 Dockerfile
    ports:
      - "9080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    image: ${DOCKER_USERNAME}/vuetify-project:latest
    build:
      context: .
      dockerfile: ./vuetify-project/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
