name: Auto Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 构建后端
      - name: Build and push backend
        working-directory: ./car-mqtt  # 确保仓库根目录下有 car-mqtt 子目录
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/car-mqtt:latest .  # 使用 Secrets 中的用户名
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/car-mqtt:latest

      # 构建前端
      - name: Build and push frontend
        working-directory: ./vuetify-project  # 确保仓库根目录下有 vuetify-project 子目录
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vuetify-project:latest .  # 使用 Secrets 中的用户名
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/vuetify-project:latest

      # 服务器端部署
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/cicd_wuyu/newTest/FiveEducation
            # 1. 将 DOCKER_USERNAME 写入服务器的 .env 文件
            echo "DOCKER_USERNAME=pulihong" > .env
            # 2. 清理旧容器和网络
            docker compose down
            # 3. 拉取最新镜像（如果镜像已推送到 Docker Hub）
            docker compose pull
            # 4. 强制重新构建镜像（如果镜像未推送，需本地构建）
            docker compose build --no-cache
            # 5. 启动新容器
            docker compose up -d
            # 传递 DOCKER_USERNAME 环境变量到服务器
