name: Group Auto Deploy
on:
  push:
    branches: [group*]  # 监听所有 group 开头的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GROUP_NAME: ${{ github.ref_name }}          # 分支名（如 group1）
      GROUP_NUMBER: ${{ github.ref_name | replace('group', '') }}  # 提取数字（如 1）
      FRONTEND_PORT: ${{ 9080 + env.GROUP_NUMBER }}  # 动态计算前端端口（9081~9093）
      BACKEND_PORT: ${{ 9180 + env.GROUP_NUMBER }}   # 动态计算后端端口（9181~9193）
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 构建并推送后端镜像
      - name: Build and push backend
        working-directory: ./car-mqtt
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/car-mqtt:${{ env.GROUP_NAME }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/car-mqtt:${{ env.GROUP_NAME }}

      # 构建并推送前端镜像
      - name: Build and push frontend
        working-directory: ./vuetify-project
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vuetify-project:${{ env.GROUP_NAME }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/vuetify-project:${{ env.GROUP_NAME }}

      # 部署到服务器
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 动态创建或更新小组目录
            DEPLOY_DIR="/www/cicd_wuyu/project/${{ env.GROUP_NAME }}"
            mkdir -p $DEPLOY_DIR
            cd $DEPLOY_DIR

            # 生成动态 docker-compose.yml
            cat <<EOL > docker-compose.yml
            version: '3.8'
            services:
              backend:
                image: ${{ secrets.DOCKER_USERNAME }}/car-mqtt:${{ env.GROUP_NAME }}
                ports:
                  - "${{ env.BACKEND_PORT }}:8080"  # 后端端口映射（如 9181:8080）
                environment:
                  - SPRING_PROFILES_ACTIVE=prod
                restart: unless-stopped

              frontend:
                image: ${{ secrets.DOCKER_USERNAME }}/vuetify-project:${{ env.GROUP_NAME }}
                ports:
                  - "${{ env.FRONTEND_PORT }}:80"  # 前端端口映射（如 9081:80）
                depends_on:
                  - backend
                restart: unless-stopped
            EOL

            # 启动或更新服务
            docker compose down || true  # 忽略首次部署时的错误
            docker compose up -d
